name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    name: Check Linden
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 4.14.2
          dune-cache: true
          opam-disable-sandboxing: true
          opam-pin: false

      - name: Install opam dependencies
        run: |
          # keep the Warblre ref in sync with the README
          opam pin add --no-action warblre.0.1.0 https://github.com/epfl-systemf/Warblre.git#c7b021e61d580b6061f0b040ca04d8e1b40e9de4
          opam install . --deps-only

      - name: Dune build
        run: opam exec -- dune build

      - name: Check compiled libraries (rocqchk)
        run: opam exec -- rocqchk -silent --output-context -R _build/default Linden _build/default/*/*.vo
